spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/clinic
    username: clinic
    password: Zman6200662
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update

api:
  tencent:
    secretId: AKIDZ1GJApOn12ta4SfjbIm5EBv9Vls1CF6k
    secretKey: YAxcFi3HSRI1ax99yb5OkDaAg2EE3g8P
    region: ap-shanghai

  # 启用 Swagger
springfox:
  documentation:
    swagger-ui:
      enabled: true